### ISSUE TITLE
Can't sync the order to DHL Express.

### ISSUE THREAD

**Issue by syed-netable** [netresearch/dhl-module-rates-express#2]
Hi,

We are trying to sync the order to DHL Express system using this module (We installed using composer from the marketplace)

Please see below screenshots

![image](https://user-images.githubusercontent.com/66652833/90336728-4d9ad700-dffb-11ea-9da8-d78eb9129121.png)

The below screenshot shows that. the $orders variable is null it is not reaching or calling to external DHL System. We just like to sync all orders placed with any carriers to be synced with DHL System

![image](https://user-images.githubusercontent.com/66652833/90336756-8cc92800-dffb-11ea-9b1c-4297d18b8f82.png)

**Comment by moehrenzahn** [comment]
Hi @syed-netable,

the DHL Express Rates module does not support shipment creation. From the Docs:

> The module only displays the available DHL Express rates in the checkout and allows the customer to select the desired product. It does not transmit the full shipment information to DHL or create shipment requests (packaging labels).

> To get and print DHL packaging labels, the shipment information needs to be exported from Magento® to DHL Express via a third-party system.

> Technically, DHL Express is an offline shipping method.
