### ISSUE TITLE
Error : ArgumentCountError: Too few arguments to function Dhl\ExpressRates\Model\Data\Form\Element\Radioset::getStyle(), 0 passed 

### ISSUE THREAD

**Issue by padhu1980** [netresearch/dhl-module-rates-express#3]
Hello,
I am using Magento latest version 2.4, getting this error. "ArgumentCountError: Too few arguments to function Dhl\ExpressRates\Model\Data\Form\Element\Radioset::getStyle(), 0 passed ". Please help in this .

**Comment by mam08ixo** [comment]
Thank you for reporting the issue. It will be fixed with the upcoming M2.4 compatibility release.

**Comment by Sebastian80** [comment]
fixed in version 1.1.0
