### ISSUE TITLE
Unknown Exception TypeError in Model/Config/ModuleConfig.php

### ISSUE THREAD

**Issue by birdman002** [netresearch/dhl-module-rates-express#4]
We recently upgraded to the most recent version 1.1.0 when we upgraded Magento to 2.3.6. We only use DHL for international shipments. We are getting this error 

`Uncaught exception 'TypeError' with message 'explode() expects parameter 2 to be string, null given' in /app/yeh5h2jcsa7mq/vendor/dhl/module-rates-express/Model/Config/ModuleConfig.php:608`

This is because we do not have selected for Allow Domestic Product. 

I believe the fix is to add a isset or not empty on the `$combinedKeys`
`$combinedKeys = isset($allowedProductsValue) ? explode(',', $allowedProductsValue): [];` or something like that. 

Hoping this is a known issue and will be fixed in the next version thank you!

**Comment by Sebastian80** [comment]
Fixed with release 1.1.1
